# Snakemake configuration file for metagenomics pipeline

# Common resources
account: "research-ceg-wm"
regular_partition: "compute"
regular_memory: "3900" # MB

# Sample information
samples:
  # - test
  - Q31-25PE0.1-1-3
  - Q32-25PE0.1-2-3
  - Q33-25PE0.1-1-11
  - Q34-25PE0.1-2-11
  - Q40-25S-1-3
  - Q41-25S-2-3
  - Q42-25S-3-3
  - Q43-25PE0.6-1-3
  - Q44-25PE0.6-2-3
  - Q45-25PE0.6-3-3
  - Q46-25PET-1-3
  - Q47-25PET-2-3
  - Q48-25PET-3-3
  - Q49-25PVC-1-3
  - Q50-25PVC-2-3
  - Q51-25PVC-3-3
  - Q52-25S-1-11
  - Q53-25S-2-11
  - Q54-25S-3-11
  - Q55-25PE0.6-1-11
  - Q56-25PE0.6-2-11
  - Q57-25PE0.6-3-11
  - Q58-25PET-1-11
  - Q59-25PET-2-11
  - Q60-25PET-3-11
  - Q61-25PVC-1-11
  - Q62-25PVC-2-11
  - Q63-25PVC-3-11
  - Q64-25S-1-0
  - Q65-25S-2-0
  - Q66-25S-3-0
  - W123-25S-1-17
  - W124-25S-2-17
  - W125-25S-3-17
  - W126-25PE0.6-1-17
  - W127-25PE0.6-2-17
  - W128-25PE0.6-3-17
  - W129-25PET-1-17
  - W130-25PET-2-17
  - W131-25PET-3-17
  - W132-25PVC-1-17
  - W133-25PVC-2-17
  - W134-25PVC-3-17

# Directory structure
input_dir: "result/0_rawdata"
fastp_dir: "result/1_fastp"
spades_dir: "result/2_spades_result"
reformated_scaffolds_dir: "result/3_reformated_scaffolds"
pyrodigal_dir: "result/4_pyrodigal"
mmseqs2_dir: "result/5_mmseqs2"


functional_annotation_dir: "result/7_functional_annotation"
kofam_dir: "result/8_kofam_annotation"
coverm_dir: "result/9_coverm"
log_dir: "log"
kraken2_dir: "result/99_kraken2"

# Tool parameters
fastp:
  threads: 4
  qualified_quality_phred: 20
  length_required: 20
  runtime: 120  # minutes
  
spades:
  threads: 32
  memory: 256
  kmers: "21,33,55,77,101,121"
  runtime: 1200  # minutes (24 hours)
  parition: "compute"

reformat_scaffolds:
  min_length: 300
  threads: 1
  runtime: 60  # minutes

pyrodigal:
  mode: "meta"
  threads: 32
  runtime: 300  # minutes

mmseqs2:
  min_seq_id: 0.9
  coverage: 0.9
  threads: 48
  runtime: 7000  # minutes
  memory: "187200M"

diamond:
  threads: 14
  evalue: 1e-5
  max_hits: 1
  runtime: 480  # minutes

eggnog:
  threads: 12
  evalue: 1e-5
  runtime: 7200  # minutes (120 hours max, use conservative 116 hours)
  chunk_size: 1000000  # number of sequences per chunk (~57 chunks for 114M sequences)
  threads_per_job: 12  # threads for each parallel job (57 jobs * 24 = 1368 CPUs total)

kofamscan:
  threads: 32
  evalue: 1e-5
  runtime: 7200  # minutes
  chunk_parts: 10  # split into 64 files

coverm:
  threads: 8
  min_read_percent_identity: 90
  min_read_aligned_percent: 50
  min_covered_fraction: 0.5
  contig_end_exclusion: 10
  runtime: 240  # minutes

bowtie2:
  threads: 8
  runtime: 7200  # minutes (5 days)
  mem_mb_per_cpu: 3900
  partition: "memory"

bowtie2_index:
  threads: 4
  runtime: 1440  # minutes (1 day)
  mem_mb_per_cpu: 3900

coverm_abundance:
  threads: 4
  min_read_percent_identity: 95
  min_read_aligned_percent: 90
  contig_end_exclusion: 0
  runtime: 1440  # minutes (1 day)
  mem_mb_per_cpu: 3900

merge_sequences:
  threads: 1
  runtime: 30  # minutes

extract_sequences:
  threads: 16
  runtime: 260  # minutes

kraken2:
  threads: 40
  confidence: 0.1
  runtime: 1200 # minutes

bracken:
  threads: 30
  kmer_length: 35
  read_length: 150
  runtime: 600  # minutes

# Database paths (adjust these paths according to your system)
databases:
  gtdb_diamond: "/scratch/qou/database/GTDB_214.1_diamond/protein_faa_reps/GTDB214_dimond.dmnd"
  gtdb_database: "/scratch/qou/database/GTDB_214.1_diamond/GTDB_database"
  eggnog_data_dir: "/scratch/qou/database/eggnog_database"
  kraken2_db: "/scratch/qou/database/kraken2"
  taxa_db: "/scratch/qou/database/taxa_DB/taxdump"
  kofam_list: "/scratch/qou/database/kofam/ko_list"  # KOfam profiles and ko_list
  kofam_profiles: "/scratch/qou/database/kofam/profiles"


# Environment/conda setup
conda_envs:
  fastp: "fastp"
  anvio: "anvio-7.1"
  prodigal: "prodigal"
  mmseq2: "mmseq2"
  diamond: "diomand"
  eggnog: "eggnog"
  coverm: "coverm"
  seqkit: "seqkit"
  base: "base"
